apiVersion: v1
entries:
  horovod:
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2021-11-18T16:48:56.42906085+01:00"
    deprecated: true
    description: DEPRECATED - A Helm chart for deploying Horovod
    digest: 4549fca604099da55fbe13746bb950f6679c5cced3fd5430c974afde6d075a59
    home: https://eng.uber.com/horovod/
    name: horovod
    sources:
    - https://github.com/uber/horovod
    - https://github.com/uber/horovod/blob/master/docs/docker.md
    urls:
    - horovod-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2021-11-18T16:48:56.430206697+01:00"
    deprecated: true
    description: DEPRECATED - A Helm chart for deploying Horovod
    digest: 224d4cfc976d1744b5baa097b0274ab5eafda18c05bd971af60a408fc18a29de
    home: https://eng.uber.com/horovod/
    name: horovod
    sources:
    - https://github.com/uber/horovod
    - https://github.com/uber/horovod/blob/master/docs/docker.md
    urls:
    - horovod-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2021-11-18T16:48:56.425987362+01:00"
    deprecated: true
    description: DEPRECATED - A Helm chart for deploying Horovod
    digest: a47b0d0d01f58956a99d388a9508db7b37d99d5c3a1ec6d8170cb4892021eb83
    home: https://eng.uber.com/horovod/
    name: horovod
    sources:
    - https://github.com/uber/horovod
    - https://github.com/uber/horovod/blob/master/docs/docker.md
    urls:
    - horovod-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2021-11-18T16:48:56.424373895+01:00"
    deprecated: true
    description: DEPRECATED - A Helm chart for deploying Horovod
    digest: fa6f6c70359bdd6be5ec2c90aa0ced706a64350d362929a2b26bbf6e501ece2b
    home: https://eng.uber.com/horovod/
    name: horovod
    sources:
    - https://github.com/uber/horovod
    - https://github.com/uber/horovod/blob/master/docs/docker.md
    urls:
    - horovod-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    appVersion: 0.12.1
    created: "2021-11-18T16:48:56.431344447+01:00"
    deprecated: true
    description: DEPRECATED - A Helm chart for deploying Horovod
    digest: 86c1bb832eb314d60051775789b4289ed3f99370d30cd0e22f3b941549bd9c7f
    home: https://eng.uber.com/horovod/
    name: horovod
    sources:
    - https://github.com/uber/horovod
    - https://github.com/uber/horovod/blob/master/docs/docker.md
    urls:
    - horovod_debug.tgz
    version: 1.0.2
generated: "2021-11-18T16:48:56.422992498+01:00"
