apiVersion: v1
entries:
  horovod:
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2021-12-08T11:33:21.879927137+01:00"
    deprecated: true
    description: DEPRECATED - A Helm chart for deploying Horovod
    digest: a5f0368ccc529bb9c21092b67989102a09a08fb9ebb784e5bbf8a439d169bffb
    home: https://eng.uber.com/horovod/
    name: horovod
    sources:
    - https://github.com/uber/horovod
    - https://github.com/uber/horovod/blob/master/docs/docker.md
    urls:
    - horovod-3.0.0.tgz
    version: 3.0.0
  spark:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 3.2.0
    created: "2021-12-08T11:33:21.888096203+01:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Spark is a fast and general-purpose cluster computing system.
    digest: 03b58b131eca2eb66a20b742f42979e7f870bcc80d615129354ec811099f798c
    home: https://github.com/bitnami/charts/tree/master/bitnami/spark
    icon: https://bitnami.com/assets/stacks/spark/img/spark-stack-220x234.png
    keywords:
    - apache
    - spark
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: spark
    sources:
    - https://github.com/bitnami/bitnami-docker-spark
    - https://spark.apache.org/
    urls:
    - spark-6.0.0.tgz
    version: 6.0.0
generated: "2021-12-08T11:33:21.878098737+01:00"
