apiVersion: v1
entries:
  horovod:
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T12:30:48.528848588Z"
    description: Horovod for PLAS platform
    digest: 43a739d97bb869810f804ee2d70e6a42b16f91712de9f76cb9acf53426ad781f
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.6.4.tgz
    version: 3.6.4
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T12:30:48.528015221Z"
    description: Horovod for PLAS platform
    digest: f01202ea86d9e5172aa6477a5ba97793cbf45bcf9c2b2d8b0de18281b3f20d2a
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.6.3.tgz
    version: 3.6.3
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T12:30:48.52753051Z"
    description: Horovod for PLAS platform
    digest: 244b991e68870ed039e842025ec9ac18ba371251f785732e080cac7c7a18b038
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.6.2.tgz
    version: 3.6.2
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T12:30:48.527027082Z"
    description: Horovod for PLAS platform
    digest: b0f415b5524edfa7e97b5c0829f5bc14d78a922f9ea34880750d8ba8cc41e0a2
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.6.1.tgz
    version: 3.6.1
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T12:30:48.52643593Z"
    description: Horovod for PLAS platform
    digest: f8367b24e26902c481bdae0eaeea9b22ab0c921d96b94cfb7e6323d9569ee44a
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.2.2.tgz
    version: 3.2.2
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T12:30:48.524250122Z"
    description: Horovod for PLAS platform
    digest: 501e458882d599fb27d12506e82184a6e280c791b83aa86f73cfbba4b30cba33
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.2.1.tgz
    version: 3.2.1
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T12:30:48.523798378Z"
    description: Horovod for PLAS platform
    digest: 9b5cd708fc7d6f6e0bdbedd1228e061a31bf89b3658620de836787626adb1b63
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.1.1.tgz
    version: 3.1.1
  spark:
  - apiVersion: v2
    appVersion: 3.2.0
    created: "2022-11-18T12:30:48.535734833Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: A Helm chart for deploying a tailored version of Spark for PLAS platform
    digest: e99644e47f12bd38d3c72e545b466c6bf8ea8b27a05254a0156dfe71e72a735f
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/spark
    keywords:
    - plas
    - spark
    name: spark
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/bitnami/bitnami-docker-spark
    - https://spark.apache.org/
    urls:
    - spark-6.0.0.tgz
    version: 6.0.0
  tesk:
  - apiVersion: v2
    appVersion: dev
    created: "2022-11-18T12:30:48.538402278Z"
    description: A Helm chart for deploying a tailored version of TESK for PLAS platform
    digest: 640e3cc196638571a01642606003b8e36ee3b78d26ce6fa7451551044e77615a
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/tesk
    keywords:
    - plas
    - tesk
    name: tesk
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/elixir-cloud-aai/TESK/tree/master/charts/tesk
    urls:
    - tesk-1.0.0.tgz
    version: 1.0.0
generated: "2022-11-18T12:30:48.5231832Z"
