apiVersion: v1
entries:
  horovod:
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T15:02:06.669688477Z"
    description: Horovod for PLAS platform
    digest: 5a9e54fa651be5c2b47507aeda43356a38f8351e53402dfc4e049cd58c01d6bf
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.6.4.tgz
    version: 3.6.4
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T15:02:06.669252668Z"
    description: Horovod for PLAS platform
    digest: d30827c6f707ef78bede6612ef9daf566dce3a43a495dcc1d4de91895b0d0f12
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.6.3.tgz
    version: 3.6.3
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T15:02:06.668654269Z"
    description: Horovod for PLAS platform
    digest: e119f28c1f97fed11eb42e47e15d285fe484d93871d3793882704db0b43a7b3a
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.6.2.tgz
    version: 3.6.2
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T15:02:06.668176835Z"
    description: Horovod for PLAS platform
    digest: ba3b2e7ee4ee2afc201f87de119a38cfaa3d9ef3e4be15b33d3a920c297d662c
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.6.1.tgz
    version: 3.6.1
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T15:02:06.667813382Z"
    description: Horovod for PLAS platform
    digest: 0ffa54f4b4bf8e09ebd66881249cca86d1a38181ec5e0e5a88dad11b5f31a909
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.2.2.tgz
    version: 3.2.2
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T15:02:06.66741389Z"
    description: Horovod for PLAS platform
    digest: 0be5f4ca2b1e45427ff3087ea9502a8e85566c987aab2c2fe524c540183a2be0
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.2.1.tgz
    version: 3.2.1
  - apiVersion: v1
    appVersion: 0.15.0
    created: "2022-11-18T15:02:06.666875554Z"
    description: Horovod for PLAS platform
    digest: 250ee7966e99949a7d7fdd2c3ed1644249a2655a8af62e67a96c147503635fd2
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/horovod
    keywords:
    - plas
    - horovod
    name: horovod
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/uber/horovod
    urls:
    - horovod-3.1.1.tgz
    version: 3.1.1
  spark:
  - apiVersion: v2
    appVersion: 3.2.0
    created: "2022-11-18T15:02:06.672050505Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: A Helm chart for deploying a tailored version of Spark for PLAS platform
    digest: e99644e47f12bd38d3c72e545b466c6bf8ea8b27a05254a0156dfe71e72a735f
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/spark
    keywords:
    - plas
    - spark
    name: spark
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/bitnami/bitnami-docker-spark
    - https://spark.apache.org/
    urls:
    - spark-6.0.0.tgz
    version: 6.0.0
  tesk:
  - apiVersion: v2
    appVersion: dev
    created: "2022-11-18T15:02:06.673530859Z"
    description: A Helm chart for deploying a tailored version of TESK for PLAS platform
    digest: 640e3cc196638571a01642606003b8e36ee3b78d26ce6fa7451551044e77615a
    home: https://github.com/PlatformedTasks/PLAS-charts/tree/main/charts/tesk
    keywords:
    - plas
    - tesk
    name: tesk
    sources:
    - https://github.com/PlatformedTasks/Documentation
    - https://github.com/elixir-cloud-aai/TESK/tree/master/charts/tesk
    urls:
    - tesk-1.0.0.tgz
    version: 1.0.0
generated: "2022-11-18T15:02:06.666334984Z"
